# Generated by Django 4.1.7 on 2023-04-05 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_newsarticle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsarticle',
            old_name='category',
            new_name='news_category',
        ),
    ]
